version: "3.7"

services:
  file-assets:
    build:
      context: .
    image: file-assets
    hostname: file-assets
    container_name: file-assets-container
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    init: true
    restart: always
